/*
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.browserautomation.mydsl.ui.internal.MydslActivator;

public class BrowserTestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.xtext.browserautomation.mydsl.BrowserTest");
	}

}
