/*
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBrowserTestScopeProvider extends DelegatingScopeProvider {
}
