/*
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BrowserTestUiModule extends AbstractBrowserTestUiModule {

	public BrowserTestUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
