/*
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BrowserTestAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/browserautomation/mydsl/parser/antlr/internal/InternalBrowserTest.tokens");
	}
}
