/*
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.browserautomation.mydsl.ide.contentassist.antlr.internal.InternalBrowserTestParser;
import org.xtext.browserautomation.mydsl.services.BrowserTestGrammarAccess;

public class BrowserTestParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BrowserTestGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BrowserTestGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTaskAccess().getNameAlternatives_1_0(), "rule__Task__NameAlternatives_1_0");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getEntreeAccess().getAlternatives(), "rule__Entree__Alternatives");
			builder.put(grammarAccess.getEntreeAccess().getAlternatives_0_2(), "rule__Entree__Alternatives_0_2");
			builder.put(grammarAccess.getPropertyAccess().getAlternatives(), "rule__Property__Alternatives");
			builder.put(grammarAccess.getActionTypeAccess().getAlternatives(), "rule__ActionType__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getBooleanAccess().getAlternatives(), "rule__Boolean__Alternatives");
			builder.put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
			builder.put(grammarAccess.getTaskAccess().getGroup(), "rule__Task__Group__0");
			builder.put(grammarAccess.getGoToAccess().getGroup(), "rule__GoTo__Group__0");
			builder.put(grammarAccess.getSelectAccess().getGroup(), "rule__Select__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getEntreeAccess().getGroup_0(), "rule__Entree__Group_0__0");
			builder.put(grammarAccess.getEntreeAccess().getGroup_2(), "rule__Entree__Group_2__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_0(), "rule__Property__Group_0__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_1(), "rule__Property__Group_1__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_2(), "rule__Property__Group_2__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_3(), "rule__Property__Group_3__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_4(), "rule__Property__Group_4__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_5(), "rule__Property__Group_5__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_6(), "rule__Property__Group_6__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_7(), "rule__Property__Group_7__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_8(), "rule__Property__Group_8__0");
			builder.put(grammarAccess.getActionCommandAccess().getGroup(), "rule__ActionCommand__Group__0");
			builder.put(grammarAccess.getActionTypeAccess().getGroup_0(), "rule__ActionType__Group_0__0");
			builder.put(grammarAccess.getActionTypeAccess().getGroup_1(), "rule__ActionType__Group_1__0");
			builder.put(grammarAccess.getActionTypeAccess().getGroup_2(), "rule__ActionType__Group_2__0");
			builder.put(grammarAccess.getActionTypeAccess().getGroup_3(), "rule__ActionType__Group_3__0");
			builder.put(grammarAccess.getTestAccess().getGroup(), "rule__Test__Group__0");
			builder.put(grammarAccess.getTestFileAccess().getTaskAssignment(), "rule__TestFile__TaskAssignment");
			builder.put(grammarAccess.getTaskAccess().getNameAssignment_1(), "rule__Task__NameAssignment_1");
			builder.put(grammarAccess.getTaskAccess().getActionsAssignment_2(), "rule__Task__ActionsAssignment_2");
			builder.put(grammarAccess.getGoToAccess().getUrlAssignment_1(), "rule__GoTo__UrlAssignment_1");
			builder.put(grammarAccess.getSelectAccess().getVarAssignment_1(), "rule__Select__VarAssignment_1");
			builder.put(grammarAccess.getSelectAccess().getPropertiesAssignment_2(), "rule__Select__PropertiesAssignment_2");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_1(), "rule__Variable__NameAssignment_1");
			builder.put(grammarAccess.getEntreeAccess().getVarAssignment_0_0(), "rule__Entree__VarAssignment_0_0");
			builder.put(grammarAccess.getEntreeAccess().getParamAssignment_0_2_0(), "rule__Entree__ParamAssignment_0_2_0");
			builder.put(grammarAccess.getEntreeAccess().getUntypedAssignment_0_2_1(), "rule__Entree__UntypedAssignment_0_2_1");
			builder.put(grammarAccess.getEntreeAccess().getStringAssignment_1(), "rule__Entree__StringAssignment_1");
			builder.put(grammarAccess.getEntreeAccess().getAccessorAssignment_2_1(), "rule__Entree__AccessorAssignment_2_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_0_0(), "rule__Property__PropAssignment_0_0");
			builder.put(grammarAccess.getPropertyAccess().getContentAssignment_0_1(), "rule__Property__ContentAssignment_0_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_1_0(), "rule__Property__PropAssignment_1_0");
			builder.put(grammarAccess.getPropertyAccess().getLabelAssignment_1_1(), "rule__Property__LabelAssignment_1_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_2_0(), "rule__Property__PropAssignment_2_0");
			builder.put(grammarAccess.getPropertyAccess().getValueAssignment_2_1(), "rule__Property__ValueAssignment_2_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_3_0(), "rule__Property__PropAssignment_3_0");
			builder.put(grammarAccess.getPropertyAccess().getAltAssignment_3_1(), "rule__Property__AltAssignment_3_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_4_0(), "rule__Property__PropAssignment_4_0");
			builder.put(grammarAccess.getPropertyAccess().getLinkAssignment_4_1(), "rule__Property__LinkAssignment_4_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_5_0(), "rule__Property__PropAssignment_5_0");
			builder.put(grammarAccess.getPropertyAccess().getTypeAssignment_5_2(), "rule__Property__TypeAssignment_5_2");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_6_0(), "rule__Property__PropAssignment_6_0");
			builder.put(grammarAccess.getPropertyAccess().getNameAssignment_6_1(), "rule__Property__NameAssignment_6_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_7_0(), "rule__Property__PropAssignment_7_0");
			builder.put(grammarAccess.getPropertyAccess().getChildAssignment_7_1(), "rule__Property__ChildAssignment_7_1");
			builder.put(grammarAccess.getPropertyAccess().getPropAssignment_8_1(), "rule__Property__PropAssignment_8_1");
			builder.put(grammarAccess.getPropertyAccess().getSubPropertiesAssignment_8_3(), "rule__Property__SubPropertiesAssignment_8_3");
			builder.put(grammarAccess.getActionCommandAccess().getVarAssignment_1(), "rule__ActionCommand__VarAssignment_1");
			builder.put(grammarAccess.getActionCommandAccess().getCommandAssignment_2(), "rule__ActionCommand__CommandAssignment_2");
			builder.put(grammarAccess.getActionTypeAccess().getActionAssignment_0_1(), "rule__ActionType__ActionAssignment_0_1");
			builder.put(grammarAccess.getActionTypeAccess().getActionAssignment_1_0(), "rule__ActionType__ActionAssignment_1_0");
			builder.put(grammarAccess.getActionTypeAccess().getValueAssignment_1_2(), "rule__ActionType__ValueAssignment_1_2");
			builder.put(grammarAccess.getActionTypeAccess().getActionAssignment_2_0(), "rule__ActionType__ActionAssignment_2_0");
			builder.put(grammarAccess.getActionTypeAccess().getTextAssignment_2_1(), "rule__ActionType__TextAssignment_2_1");
			builder.put(grammarAccess.getActionTypeAccess().getActionAssignment_3_0(), "rule__ActionType__ActionAssignment_3_0");
			builder.put(grammarAccess.getActionTypeAccess().getOptionAssignment_3_1(), "rule__ActionType__OptionAssignment_3_1");
			builder.put(grammarAccess.getTestAccess().getVarAssignment_1(), "rule__Test__VarAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BrowserTestGrammarAccess grammarAccess;

	@Override
	protected InternalBrowserTestParser createParser() {
		InternalBrowserTestParser result = new InternalBrowserTestParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BrowserTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BrowserTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
