/**
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.browserTest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserTestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browserTest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/browserautomation/mydsl/BrowserTest";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browserTest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserTestPackage eINSTANCE = org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.TestFileImpl <em>Test File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.TestFileImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getTestFile()
   * @generated
   */
  int TEST_FILE = 0;

  /**
   * The feature id for the '<em><b>Task</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FILE__TASK = 0;

  /**
   * The number of structural features of the '<em>Test File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.TaskImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getTask()
   * @generated
   */
  int TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__ACTIONS = 1;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.ActionImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getAction()
   * @generated
   */
  int ACTION = 2;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.GoToImpl <em>Go To</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.GoToImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getGoTo()
   * @generated
   */
  int GO_TO = 3;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO__URL = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go To</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_TO_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.SelectImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 4;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__VAR = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__PROPERTIES = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.VariableImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.EntreeImpl <em>Entree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.EntreeImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getEntree()
   * @generated
   */
  int ENTREE = 6;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__VAR = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__PARAM = 1;

  /**
   * The feature id for the '<em><b>Untyped</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__UNTYPED = 2;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__STRING = 3;

  /**
   * The feature id for the '<em><b>Accessor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE__ACCESSOR = 4;

  /**
   * The number of structural features of the '<em>Entree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTREE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.PropertyImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 7;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__CONTENT = 0;

  /**
   * The feature id for the '<em><b>Label</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__LABEL = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__VALUE = 2;

  /**
   * The feature id for the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__ALT = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 5;

  /**
   * The feature id for the '<em><b>Child</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__CHILD = 6;

  /**
   * The feature id for the '<em><b>Sub Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__SUB_PROPERTIES = 7;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.ActionCommandImpl <em>Action Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.ActionCommandImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getActionCommand()
   * @generated
   */
  int ACTION_COMMAND = 8;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_COMMAND__VAR = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_COMMAND__COMMAND = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Action Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_COMMAND_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.ActionTypeImpl <em>Action Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.ActionTypeImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getActionType()
   * @generated
   */
  int ACTION_TYPE = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_TYPE__VALUE = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_TYPE__TEXT = 1;

  /**
   * The feature id for the '<em><b>Option</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_TYPE__OPTION = 2;

  /**
   * The number of structural features of the '<em>Action Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.TestImpl
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getTest()
   * @generated
   */
  int TEST = 10;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__VAR = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.Type <em>Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.Type
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getType()
   * @generated
   */
  int TYPE = 11;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.Boolean <em>Boolean</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.Boolean
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 12;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.Attribute <em>Attribute</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.Attribute
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 13;

  /**
   * The meta object id for the '{@link org.xtext.browserautomation.mydsl.browserTest.Accessor <em>Accessor</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.browserautomation.mydsl.browserTest.Accessor
   * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getAccessor()
   * @generated
   */
  int ACCESSOR = 14;


  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.TestFile <em>Test File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test File</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.TestFile
   * @generated
   */
  EClass getTestFile();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.browserautomation.mydsl.browserTest.TestFile#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Task</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.TestFile#getTask()
   * @see #getTestFile()
   * @generated
   */
  EReference getTestFile_Task();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.browserautomation.mydsl.browserTest.Task#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Task#getActions()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.GoTo <em>Go To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go To</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.GoTo
   * @generated
   */
  EClass getGoTo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.GoTo#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.GoTo#getUrl()
   * @see #getGoTo()
   * @generated
   */
  EAttribute getGoTo_Url();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.Select#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Select#getVar()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Var();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.browserautomation.mydsl.browserTest.Select#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Select#getProperties()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Properties();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.Entree <em>Entree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entree</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Entree
   * @generated
   */
  EClass getEntree();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Entree#getVar()
   * @see #getEntree()
   * @generated
   */
  EReference getEntree_Var();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Param</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Entree#getParam()
   * @see #getEntree()
   * @generated
   */
  EAttribute getEntree_Param();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getUntyped <em>Untyped</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Untyped</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Entree#getUntyped()
   * @see #getEntree()
   * @generated
   */
  EAttribute getEntree_Untyped();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Entree#getString()
   * @see #getEntree()
   * @generated
   */
  EAttribute getEntree_String();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getAccessor <em>Accessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Accessor</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Entree#getAccessor()
   * @see #getEntree()
   * @generated
   */
  EAttribute getEntree_Accessor();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Content</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getContent()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Content();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Label</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getLabel()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Label();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getValue()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getAlt <em>Alt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Alt</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getAlt()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Alt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getChild <em>Child</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Child</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getChild()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Child();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getSubProperties <em>Sub Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sub Properties</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Property#getSubProperties()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_SubProperties();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.ActionCommand <em>Action Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Command</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.ActionCommand
   * @generated
   */
  EClass getActionCommand();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.browserautomation.mydsl.browserTest.ActionCommand#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.ActionCommand#getVar()
   * @see #getActionCommand()
   * @generated
   */
  EReference getActionCommand_Var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.ActionCommand#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Command</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.ActionCommand#getCommand()
   * @see #getActionCommand()
   * @generated
   */
  EReference getActionCommand_Command();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.ActionType <em>Action Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action Type</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.ActionType
   * @generated
   */
  EClass getActionType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.browserautomation.mydsl.browserTest.ActionType#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.ActionType#getValue()
   * @see #getActionType()
   * @generated
   */
  EAttribute getActionType_Value();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.ActionType#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.ActionType#getText()
   * @see #getActionType()
   * @generated
   */
  EReference getActionType_Text();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.ActionType#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Option</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.ActionType#getOption()
   * @see #getActionType()
   * @generated
   */
  EReference getActionType_Option();

  /**
   * Returns the meta object for class '{@link org.xtext.browserautomation.mydsl.browserTest.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.browserautomation.mydsl.browserTest.Test#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Test#getVar()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Var();

  /**
   * Returns the meta object for enum '{@link org.xtext.browserautomation.mydsl.browserTest.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Type
   * @generated
   */
  EEnum getType();

  /**
   * Returns the meta object for enum '{@link org.xtext.browserautomation.mydsl.browserTest.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Boolean</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Boolean
   * @generated
   */
  EEnum getBoolean();

  /**
   * Returns the meta object for enum '{@link org.xtext.browserautomation.mydsl.browserTest.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Attribute</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Attribute
   * @generated
   */
  EEnum getAttribute();

  /**
   * Returns the meta object for enum '{@link org.xtext.browserautomation.mydsl.browserTest.Accessor <em>Accessor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Accessor</em>'.
   * @see org.xtext.browserautomation.mydsl.browserTest.Accessor
   * @generated
   */
  EEnum getAccessor();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserTestFactory getBrowserTestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.TestFileImpl <em>Test File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.TestFileImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getTestFile()
     * @generated
     */
    EClass TEST_FILE = eINSTANCE.getTestFile();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_FILE__TASK = eINSTANCE.getTestFile_Task();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.TaskImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__ACTIONS = eINSTANCE.getTask_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.ActionImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.GoToImpl <em>Go To</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.GoToImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getGoTo()
     * @generated
     */
    EClass GO_TO = eINSTANCE.getGoTo();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO_TO__URL = eINSTANCE.getGoTo_Url();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.SelectImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__VAR = eINSTANCE.getSelect_Var();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__PROPERTIES = eINSTANCE.getSelect_Properties();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.VariableImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.EntreeImpl <em>Entree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.EntreeImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getEntree()
     * @generated
     */
    EClass ENTREE = eINSTANCE.getEntree();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTREE__VAR = eINSTANCE.getEntree_Var();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTREE__PARAM = eINSTANCE.getEntree_Param();

    /**
     * The meta object literal for the '<em><b>Untyped</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTREE__UNTYPED = eINSTANCE.getEntree_Untyped();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTREE__STRING = eINSTANCE.getEntree_String();

    /**
     * The meta object literal for the '<em><b>Accessor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTREE__ACCESSOR = eINSTANCE.getEntree_Accessor();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.PropertyImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__CONTENT = eINSTANCE.getProperty_Content();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__LABEL = eINSTANCE.getProperty_Label();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__VALUE = eINSTANCE.getProperty_Value();

    /**
     * The meta object literal for the '<em><b>Alt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__ALT = eINSTANCE.getProperty_Alt();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Child</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__CHILD = eINSTANCE.getProperty_Child();

    /**
     * The meta object literal for the '<em><b>Sub Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__SUB_PROPERTIES = eINSTANCE.getProperty_SubProperties();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.ActionCommandImpl <em>Action Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.ActionCommandImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getActionCommand()
     * @generated
     */
    EClass ACTION_COMMAND = eINSTANCE.getActionCommand();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_COMMAND__VAR = eINSTANCE.getActionCommand_Var();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_COMMAND__COMMAND = eINSTANCE.getActionCommand_Command();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.ActionTypeImpl <em>Action Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.ActionTypeImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getActionType()
     * @generated
     */
    EClass ACTION_TYPE = eINSTANCE.getActionType();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION_TYPE__VALUE = eINSTANCE.getActionType_Value();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_TYPE__TEXT = eINSTANCE.getActionType_Text();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION_TYPE__OPTION = eINSTANCE.getActionType_Option();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.TestImpl
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__VAR = eINSTANCE.getTest_Var();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.Type <em>Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.Type
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getType()
     * @generated
     */
    EEnum TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.Boolean <em>Boolean</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.Boolean
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getBoolean()
     * @generated
     */
    EEnum BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.Attribute <em>Attribute</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.Attribute
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getAttribute()
     * @generated
     */
    EEnum ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '{@link org.xtext.browserautomation.mydsl.browserTest.Accessor <em>Accessor</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.browserautomation.mydsl.browserTest.Accessor
     * @see org.xtext.browserautomation.mydsl.browserTest.impl.BrowserTestPackageImpl#getAccessor()
     * @generated
     */
    EEnum ACCESSOR = eINSTANCE.getAccessor();

  }

} //BrowserTestPackage
