/**
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.browserTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entree</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getParam <em>Param</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getUntyped <em>Untyped</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getString <em>String</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getAccessor <em>Accessor</em>}</li>
 * </ul>
 *
 * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getEntree()
 * @model
 * @generated
 */
public interface Entree extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(Variable)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getEntree_Var()
   * @model containment="true"
   * @generated
   */
  Variable getVar();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Variable value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.browserautomation.mydsl.browserTest.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' attribute.
   * @see org.xtext.browserautomation.mydsl.browserTest.Attribute
   * @see #setParam(Attribute)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getEntree_Param()
   * @model
   * @generated
   */
  Attribute getParam();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getParam <em>Param</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' attribute.
   * @see org.xtext.browserautomation.mydsl.browserTest.Attribute
   * @see #getParam()
   * @generated
   */
  void setParam(Attribute value);

  /**
   * Returns the value of the '<em><b>Untyped</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Untyped</em>' attribute.
   * @see #setUntyped(String)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getEntree_Untyped()
   * @model
   * @generated
   */
  String getUntyped();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getUntyped <em>Untyped</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Untyped</em>' attribute.
   * @see #getUntyped()
   * @generated
   */
  void setUntyped(String value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getEntree_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

  /**
   * Returns the value of the '<em><b>Accessor</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.browserautomation.mydsl.browserTest.Accessor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Accessor</em>' attribute.
   * @see org.xtext.browserautomation.mydsl.browserTest.Accessor
   * @see #setAccessor(Accessor)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getEntree_Accessor()
   * @model
   * @generated
   */
  Accessor getAccessor();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Entree#getAccessor <em>Accessor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Accessor</em>' attribute.
   * @see org.xtext.browserautomation.mydsl.browserTest.Accessor
   * @see #getAccessor()
   * @generated
   */
  void setAccessor(Accessor value);

} // Entree
