/**
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.browserTest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getContent <em>Content</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getLabel <em>Label</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getAlt <em>Alt</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getChild <em>Child</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Property#getSubProperties <em>Sub Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference.
   * @see #setContent(Entree)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_Content()
   * @model containment="true"
   * @generated
   */
  Entree getContent();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getContent <em>Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' containment reference.
   * @see #getContent()
   * @generated
   */
  void setContent(Entree value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' containment reference.
   * @see #setLabel(Entree)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_Label()
   * @model containment="true"
   * @generated
   */
  Entree getLabel();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getLabel <em>Label</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' containment reference.
   * @see #getLabel()
   * @generated
   */
  void setLabel(Entree value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Entree)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_Value()
   * @model containment="true"
   * @generated
   */
  Entree getValue();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Entree value);

  /**
   * Returns the value of the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' containment reference.
   * @see #setAlt(Entree)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_Alt()
   * @model containment="true"
   * @generated
   */
  Entree getAlt();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getAlt <em>Alt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' containment reference.
   * @see #getAlt()
   * @generated
   */
  void setAlt(Entree value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.browserautomation.mydsl.browserTest.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.browserautomation.mydsl.browserTest.Type
   * @see #setType(Type)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.browserautomation.mydsl.browserTest.Type
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Child</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child</em>' attribute.
   * @see #setChild(int)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_Child()
   * @model
   * @generated
   */
  int getChild();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Property#getChild <em>Child</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Child</em>' attribute.
   * @see #getChild()
   * @generated
   */
  void setChild(int value);

  /**
   * Returns the value of the '<em><b>Sub Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.browserautomation.mydsl.browserTest.Property}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Properties</em>' containment reference list.
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getProperty_SubProperties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getSubProperties();

} // Property
