/**
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.browserTest;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Select#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.browserautomation.mydsl.browserTest.Select#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getSelect()
 * @model
 * @generated
 */
public interface Select extends Action
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(Variable)
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getSelect_Var()
   * @model containment="true"
   * @generated
   */
  Variable getVar();

  /**
   * Sets the value of the '{@link org.xtext.browserautomation.mydsl.browserTest.Select#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Variable value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.browserautomation.mydsl.browserTest.Property}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage#getSelect_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

} // Select
