/*
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.browserautomation.mydsl.browserTest.ActionCommand;
import org.xtext.browserautomation.mydsl.browserTest.ActionType;
import org.xtext.browserautomation.mydsl.browserTest.BrowserTestPackage;
import org.xtext.browserautomation.mydsl.browserTest.Entree;
import org.xtext.browserautomation.mydsl.browserTest.GoTo;
import org.xtext.browserautomation.mydsl.browserTest.Property;
import org.xtext.browserautomation.mydsl.browserTest.Select;
import org.xtext.browserautomation.mydsl.browserTest.Task;
import org.xtext.browserautomation.mydsl.browserTest.Test;
import org.xtext.browserautomation.mydsl.browserTest.TestFile;
import org.xtext.browserautomation.mydsl.browserTest.Variable;
import org.xtext.browserautomation.mydsl.services.BrowserTestGrammarAccess;

@SuppressWarnings("all")
public class BrowserTestSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BrowserTestGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BrowserTestPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BrowserTestPackage.ACTION_COMMAND:
				sequence_ActionCommand(context, (ActionCommand) semanticObject); 
				return; 
			case BrowserTestPackage.ACTION_TYPE:
				sequence_ActionType(context, (ActionType) semanticObject); 
				return; 
			case BrowserTestPackage.ENTREE:
				sequence_Entree(context, (Entree) semanticObject); 
				return; 
			case BrowserTestPackage.GO_TO:
				sequence_GoTo(context, (GoTo) semanticObject); 
				return; 
			case BrowserTestPackage.PROPERTY:
				sequence_Property(context, (Property) semanticObject); 
				return; 
			case BrowserTestPackage.SELECT:
				sequence_Select(context, (Select) semanticObject); 
				return; 
			case BrowserTestPackage.TASK:
				sequence_Task(context, (Task) semanticObject); 
				return; 
			case BrowserTestPackage.TEST:
				sequence_Test(context, (Test) semanticObject); 
				return; 
			case BrowserTestPackage.TEST_FILE:
				sequence_TestFile(context, (TestFile) semanticObject); 
				return; 
			case BrowserTestPackage.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns ActionCommand
	 *     ActionCommand returns ActionCommand
	 *
	 * Constraint:
	 *     (var=Variable command=ActionType)
	 * </pre>
	 */
	protected void sequence_ActionCommand(ISerializationContext context, ActionCommand semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BrowserTestPackage.Literals.ACTION_COMMAND__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BrowserTestPackage.Literals.ACTION_COMMAND__VAR));
			if (transientValues.isValueTransient(semanticObject, BrowserTestPackage.Literals.ACTION_COMMAND__COMMAND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BrowserTestPackage.Literals.ACTION_COMMAND__COMMAND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getActionCommandAccess().getVarVariableParserRuleCall_1_0(), semanticObject.getVar());
		feeder.accept(grammarAccess.getActionCommandAccess().getCommandActionTypeParserRuleCall_2_0(), semanticObject.getCommand());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ActionType returns ActionType
	 *
	 * Constraint:
	 *     (action='[CLICK]' | (action='[CHECK]' value=Boolean) | (action='[SET-TEXT]' text=Entree) | (action='[CHOOSE]' option=Entree))
	 * </pre>
	 */
	protected void sequence_ActionType(ISerializationContext context, ActionType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Entree returns Entree
	 *
	 * Constraint:
	 *     ((var=Variable (param=Attribute | untyped=ID)) | string=STRING | accessor=Accessor)
	 * </pre>
	 */
	protected void sequence_Entree(ISerializationContext context, Entree semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns GoTo
	 *     GoTo returns GoTo
	 *
	 * Constraint:
	 *     url=STRING
	 * </pre>
	 */
	protected void sequence_GoTo(ISerializationContext context, GoTo semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BrowserTestPackage.Literals.GO_TO__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BrowserTestPackage.Literals.GO_TO__URL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGoToAccess().getUrlSTRINGTerminalRuleCall_1_0(), semanticObject.getUrl());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Property returns Property
	 *
	 * Constraint:
	 *     (
	 *         (prop='[CONTENT]' content=Entree) | 
	 *         (prop='[LABEL]' label=Entree) | 
	 *         (prop='[VALUE]' value=Entree) | 
	 *         (prop='[ALT]' alt=Entree) | 
	 *         (prop='[LINK]' link=Entree) | 
	 *         (prop='[TYPE]' type=Type) | 
	 *         (prop='[NAME]' name=STRING) | 
	 *         (prop='[NTH-CHILD]' child=INT) | 
	 *         (prop='[PARENT]' subProperties+=Property*)
	 *     )
	 * </pre>
	 */
	protected void sequence_Property(ISerializationContext context, Property semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns Select
	 *     Select returns Select
	 *
	 * Constraint:
	 *     (var=Variable properties+=Property*)
	 * </pre>
	 */
	protected void sequence_Select(ISerializationContext context, Select semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Task returns Task
	 *
	 * Constraint:
	 *     ((name=ID | name=STRING) actions+=Action*)
	 * </pre>
	 */
	protected void sequence_Task(ISerializationContext context, Task semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TestFile returns TestFile
	 *
	 * Constraint:
	 *     task+=Task+
	 * </pre>
	 */
	protected void sequence_TestFile(ISerializationContext context, TestFile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Action returns Test
	 *     Test returns Test
	 *
	 * Constraint:
	 *     var=Variable
	 * </pre>
	 */
	protected void sequence_Test(ISerializationContext context, Test semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BrowserTestPackage.Literals.TEST__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BrowserTestPackage.Literals.TEST__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTestAccess().getVarVariableParserRuleCall_1_0(), semanticObject.getVar());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Variable returns Variable
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_Variable(ISerializationContext context, Variable semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BrowserTestPackage.Literals.VARIABLE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BrowserTestPackage.Literals.VARIABLE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
