/*
 * generated by Xtext 2.36.0
 */
package org.xtext.browserautomation.mydsl.ide;


/**
 * Use this class to register ide components.
 */
public class BrowserTestIdeModule extends AbstractBrowserTestIdeModule {
}
